server:
  port: ${SERVER_PORT:8081}


spring:
  application:
    name: pasajeros-ms
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/pasajeros_db?createDatabaseIfNotExist=true&useSSL=false}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true



# Configuración de Logs 
logging:
  level:
    cl.duoc.sigft.pasajeros_ms: INFO
    
