server:
  port: ${PORT:8085}


spring:
  application:
    name: integracion-ms
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/integracion_db?createDatabaseIfNotExist=true&useSSL=false}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      initialization-fail-timeout: 60000
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

logging:
  level:
    cl.duoc.sigft.integracion_ms: INFO

# URL simulada de API Argentina (R.6)
integracion:
  aduana-argentina:
    url: https://api.aduana.gob.ar/v1
    timeout-ms: 5000

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
    initial-instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

management:
  endpoints:
    web:
      exposure:
        include: "*"
